### PR TITLE
checkstyle fixes

### PR DESCRIPTION
**Pull request by leonorader**

### CODE REVIEW

**Comment by kinow** [comment]
That was quick!!! ⚡️ Thanks!

@leonorader could you just remove the `.idea/` files? We can include that to `.gitignore` too if necessary.

**Comment by leonorader** [comment]
Sure, I removed the files and added .idea to gitignore, sorry for that! I usually have it in gitignore and this time I forgot to double check! :)

**Comment by kinow** [comment]
> Sure, I removed the files and added .idea to gitignore, sorry for that! I usually have it in gitignore and this time I forgot to double check! :)

I could have added them too, sorry. GitHub has a comprehensive template gitignore for Java files that I normally use but forgot to apply here (will do it some other day).

**Comment by kinow** [comment]
Tested locally after re-enabling checkstyle in `pom.xml` (the failures on errors or warnings were disabled) and everything passed fine. Thanks a ton @leonorader !!! :clap: :clap: Merged locally and pushed to master.

**Pull request closed without merging**
